/**
 * IPA packaging & remote build orchestration.
 * Native Swift compilation requires macOS/Xcode — we support:
 *  1. Local .app → .ipa packaging (for pre-built or Theos output)
 *  2. GitHub Actions macOS runner build (trigger from Windows)
 */
const fs = require('fs');
const path = require('path');
const archiver = require('archiver');
const config = require('../config');
const { runCommand } = require('./shell');

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

async function packageAppToIpa(appPath, outputIpa, onLog) {
  if (!fs.existsSync(appPath)) {
    throw new Error(`App bundle not found: ${appPath}`);
  }

  ensureDir(path.dirname(outputIpa));

  return new Promise((resolve, reject) => {
    const output = fs.createWriteStream(outputIpa);
    const archive = archiver('zip', { zlib: { level: 9 } });

    output.on('close', () => {
      onLog?.(`IPA created: ${outputIpa} (${archive.pointer()} bytes)\n`);
      resolve({ path: outputIpa, size: archive.pointer() });
    });

    archive.on('error', reject);
    archive.on('entry', (entry) => onLog?.(`  + ${entry.name}\n`));

    archive.pipe(output);
    archive.directory(appPath, 'Payload/' + path.basename(appPath));
    archive.finalize();
  });
}

function generateWorkflow(projectName, bundleId) {
  return `# Auto-generated by Skibidi IPA Builder
# Builds Swift iOS app on macOS GitHub runner (no Mac needed locally)

name: Build iOS IPA

on:
  workflow_dispatch:
  push:
    branches: [main, master]
    paths:
      - 'projects/${projectName}/**'

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer || true

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode project
        working-directory: projects/${projectName}
        run: xcodegen generate

      - name: Build unsigned .app
        working-directory: projects/${projectName}
        run: |
          xcodebuild -project ${projectName}.xcodeproj \\
            -scheme ${projectName} \\
            -configuration Debug \\
            -destination 'generic/platform=iOS' \\
            -derivedDataPath build/DerivedData \\
            CODE_SIGNING_ALLOWED=NO \\
            build

      - name: Package IPA
        working-directory: projects/${projectName}
        run: |
          APP=\$(find build/DerivedData -name '*.app' -type d | head -1)
          mkdir -p build/Payload
          cp -R "\$APP" "build/Payload/"
          cd build && zip -r ../${projectName}.ipa Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${projectName}-ipa
          path: projects/${projectName}/${projectName}.ipa
`;
}

function writeWorkflow(projectName, bundleId) {
  const workflowDir = path.join(config.root, '.github', 'workflows');
  ensureDir(workflowDir);
  const workflowPath = path.join(workflowDir, `build-${projectName}.yml`);
  fs.writeFileSync(workflowPath, generateWorkflow(projectName, bundleId));
  return workflowPath;
}

function createSwiftProject(name, bundleId) {
  const projectDir = path.join(config.projectsDir, name);
  const srcDir = path.join(projectDir, 'Sources', name);

  ensureDir(srcDir);

  const projectYml = `name: ${name}
options:
  bundleIdPrefix: com.skibidi
  deploymentTarget:
    iOS: "15.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
targets:
  ${name}:
    type: application
    platform: iOS
    sources:
      - path: Sources/${name}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${bundleId}
        INFOPLIST_KEY_CFBundleDisplayName: ${name}
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
`;

  const appSwift = `import SwiftUI

@main
struct ${name}App: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
`;

  const contentView = `import SwiftUI

struct ContentView: View {
    var body: some View {
        VStack(spacing: 16) {
            Image(systemName: "iphone")
                .font(.system(size: 64))
                .foregroundStyle(.blue)
            Text("Hello from ${name}!")
                .font(.title2.bold())
            Text("Built with Skibidi IPA Builder")
                .font(.caption)
                .foregroundStyle(.secondary)
        }
        .padding()
    }
}

#Preview {
    ContentView()
}
`;

  fs.writeFileSync(path.join(projectDir, 'project.yml'), projectYml);
  fs.writeFileSync(path.join(srcDir, `${name}App.swift`), appSwift);
  fs.writeFileSync(path.join(srcDir, 'ContentView.swift'), contentView);

  writeWorkflow(name, bundleId);

  return projectDir;
}

async function localBuildStatus(projectName) {
  const projectDir = path.join(config.projectsDir, projectName);
  const ipaPath = path.join(projectDir, `${projectName}.ipa`);
  const appSearch = path.join(projectDir, 'build');

  return {
    projectDir,
    hasProjectYml: fs.existsSync(path.join(projectDir, 'project.yml')),
    hasIpa: fs.existsSync(ipaPath),
    ipaPath: fs.existsSync(ipaPath) ? ipaPath : null,
    workflowPath: path.join(config.root, '.github', 'workflows', `build-${projectName}.yml`),
  };
}

module.exports = {
  packageAppToIpa,
  createSwiftProject,
  writeWorkflow,
  localBuildStatus,
  generateWorkflow,
};
